Site: Stahnkage.com
# Place logo in styles
Favicon: favicon.ico
Logo: logo.gif
LDAPInfo:
  Host:  duo.stahnkage.com
  BindDN: uid=stahnma,ou=people,dc=stahnkage,dc=com
  #BindPW: You can put a PW here, or use ENV variable LDAP_PASSWORD
  BaseDN: dc=stahnkage,dc=com

UserWritableAttrs:
  Shell: loginShell
  Mail: mail
  Phone: telephoneNumber
  PagerMail: pager
#  Password: userPassword
  Phone: telephoneNumber
  #FIXME figure that part out
  #loginShells:
  #  - /bin/bash
  #  - /bin/zsh
  #  - /sbin/sh
