Site: Example Organization Inc
# Place logo in styles
Style: style
Favicon: favicon.ico
Logo: logo.png
AltLogo: LDAP Self Service
LDAPInfo:
  Host:  ldap.example.com
  BaseDN: dc=example,dc=com
  # For password resets and such, this is required
  BindDN: uid=pwadmin,ou=people,dc=example,dc=com
  #BindPW: You can put a PW here, or use ENV variable LDAP_PASSWORD
  SSL: true

# Note that you must modify ACIs in your LDAP directory to ensure
#  users have self-write for any attribute in this list
UserWritableAttrs:
  Mail: mail
  Phone: telephoneNumber
  Pager: pager

# The following Attributes will show up as 'grayed out' when
# a user is managing their account.  
ReadOnlyAttrs:
  Login: uid

#The following information is used for Password Reset Emails
PWReset:
  # Time a reset session is kept alive (in hours)
  Timeout: 24
  # Who is the email from
  FromAlias: Example Org Administrator
  FromAddress: noreply@example.com

UserSetup:
  AltSiteNames:
    - example.org
    - example.com
  ExampleHostname: yoda
  DefaultGroupID: 100
  LoginShell: /bin/bash
  HomePrefix: /home
  ObjectClasses:
    - top
    - person
    - organizationalPerson
    - inetorgperson
    - posixAccount
    - shadowAccount
  AccountOU: ou=people
  ResetURI: "https://www.exmple.com/lssm/index.rb?action=forgot"

